test: Add test for strategy guard
getsentry/arroyo pull request #218
Opened 2023-04-26 22:22 UTC by lynnagara

Add a test for https://github.com/getsentry/arroyo/pull/217 to ensure guard.close() and guard.join() does not raise an error

2023-04-27 14:31 UTC, evanh approved these changes

2023-04-27 14:51 UTC, untitaker requested changes
i believe this test should be in `test_all`. You're just testing the guard strategy here, but the guard strategy is not something that _wraps_ all strategies

2023-04-27 14:52 UTC, untitaker commented
it may also be that some strategies that do not use guard still have the bug that #217 was supposed to fix?

2023-04-28 21:29 UTC, lynnagara commented
> it may also be that some strategies that do not use guard still have the bug that #217 was supposed to fix?

You are right.... RunTaskInThreads was also not handled correctly. Updated with the fix for that strategy and the test for all of the run task family of strategies.

2023-05-01 18:03 UTC, merged