feat: A better API for abandoning messages on shutdown
getsentry/arroyo pull request #356
Opened 2024-04-13 00:03 UTC by lynnagara

There were a number of incidents recently (e.g. inc-706) where consumers were not shutdown cleanly as they were unable to finish processing all pending messages before they get kicked out by the broker or kubernetes due to timeouts.

In order to facilitate quicker shutdown, this change aims to make it easier for consumers to drop work and shutdown faster instead of attempting to finish processing every message that has been queued.

A number of strategies that support asynchronous processing (run task in threads, run task with multiprocessing, reduce, unfold, batch, unbatch) now support an optional `abandon_messages_on_shutdown` argument in the constructor. If this is set to true, any work in this processing strategy will be immediately dropped on shutdown. The default is false for backward compatibility.

2024-04-15 22:30 UTC, fpacifici requested changes
Originally the timeout parameter on the join method was supposed to guarantee that we would always complete the join method before the deadline had passed and the consumer was kicked out. 

Is there a reason we cannot use that as we should ? 
Since this will change the public interface of those strategies I think we should not introduce two ways to achieve the same thing: "ensuring the join method returns before the consumer is kicked out"

2024-04-15 22:30 UTC, fpacifici commented on arroyo/processing/strategies/run_task_in_threads.py
> +        self.__abandon_messages_on_shutdown = abandon_messsages_on_shutdown
Technically join may not only be executed at shutdown. 
I would rename it as abandon messages on join.

2024-05-17 13:55 UTC, untitaker commented
FYI something similar to this was implemented in https://github.com/getsentry/snuba/pull/5918

2024-10-15 20:50 UTC, volokluev commented
closing due to staleness, feel free to reopen

2024-10-15 20:50 UTC, closed without merging